### ISSUE TITLE
Thoughts on Standard Formats

### ISSUE THREAD

**Issue by systmkor** [larsbrinkhoff/awesome-cpus#1]
There is some inconsistency with file formats. Some files are compressed (e.g. with bz2) and some are postscript files. It would be nice that all of the documentation are uncompressed by default, or at least consistent. I understand that this would cause the data usage of the repo a lot faster (so more discussion is probably in order). The original formats should probably exist in the repo however it would be nice to provide a PDF version of a postcript document since that will be more accessible to users. 

These are just some thoughts for discussion.

p.s.
This project is awesome, especially for those trying to enter into the low-level coding space.

**Comment by larsbrinkhoff** [comment]
Thanks, I've been meaning to uncompress all files.  I'm pushing that now.

However, I'm not going to convert PostScript to PDF myself.  Happy to accept pull requests, though.

**Comment by larsbrinkhoff** [comment]
All `.bz2` files have been uncompressed.  Case closed... for now.
