### ISSUE TITLE
How do one move a folder to a subrepo?

### ISSUE THREAD

**Issue by The-Blue-Wizard** [larsbrinkhoff/awesome-cpus#12]
Can you give me the instructions on how to move the folder from my (forked) repo to a subrepo under the awesome-cpus organization? Thanks!

Once all folders are moved over there, I can then delete my forked repo, and free up some spaces :-)

**Comment by larsbrinkhoff** [comment]
Depends on how careful you want to be with the move.  But a quick-and-dirty version is:

1. Create a new repository in the awesome-cpus organization.  If you don't have permission to do that, I'll try to fix that.
2. Make a local clone of the repository.
3. Copy all the files from a folder, to the repository.  All files should be at the top level of the new repository.
4. Commit and push.
5. Remove the old folder with `git rm -r`.  If you're moving files.  Skip this if you're adding a new CPU.
6. Make a new subrepository in the `awesome-cpus` repository with the `git submodule add` command.  The first argument should be the URL of the new repository, and the second argument should be the name of the CPU folder.
7. Commit, push, post a pull request.

One last step would be to clean up the `awesome-cpus` repository data.  The old files are still there.  This is on my TODO list.

**Comment by larsbrinkhoff** [comment]
> Once all folders are moved over there

Hey, you don't need to move **all** folders!  Just the extraordinarily big ones.

**Comment by larsbrinkhoff** [comment]
I think this can be closed.
