### ISSUE TITLE
Make the list more awesome!

### ISSUE THREAD

**Issue by drom** [larsbrinkhoff/awesome-cpus#17]
Can we make this list compliant with https://github.com/sindresorhus/awesome ?

**[URL to the list here.]**

**[Explain what this list is all about and why it should be included here.]**

# ALL THE BELOW CHECKBOXES SHOULD BE DONE AND CHECKED AND THE ABOVE PLACEHOLDERS SHOULD BE FILLED IN BEFORE SUBMITTING A PULL REQUEST!

- [x] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [x] This pull request has a descriptive title. *(For example: `Add Node.js`)*
- The list I added
	- [x] **has been around for at least 20 days,**
	- [x] is a non-generated Markdown file in a GitHub repo,
	- [x] is not a duplicate,
	- [x] only has awesome items with descriptions *(Awesome lists are curations of the best, not of everything)*,
	- [x] contains the [awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge) on the right side of the list heading,
	- [x] has a Table of Contents section named `Contents` as the first section,
	- [x] has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license) *(Meaning something like CC0, NOT a code licence like MIT, BSD, Apache, etc)*,
	- [x] has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines),
	- [x] has been checked for inconsistent formatting, spelling, and grammar *(This includes starting each link description with an uppercase character and ending it with a period `.`, and consistent naming)*,
	- [x] has been added at the bottom of the appropriate category.

**Comment by drom** [comment]
What kind of license would be appropriate for the project?

**Comment by larsbrinkhoff** [comment]
> Can we make this list compliant with https://github.com/sindresorhus/awesome ?

I thought about that when I created this list.  Some of the requirements don't seem to fit well with the goal of this project.  But sure, we could try.

> What kind of license would be appropriate for the project?

"Awesome awesome" recommends CC0.  I would be fine with that.

**Comment by larsbrinkhoff** [comment]
I fixed these:

- [ ] contains the awesome badge on the right side of the list heading,
- [ ] has a Table of Contents section named Contents as the first section,

**Comment by drom** [comment]
CC0 LGTM

**Comment by larsbrinkhoff** [comment]
I'm not going to submit awecpus-cpus to the awesome list myself.  I don't have more time to work on this now.

**Comment by drom** [comment]
I can submit.

**Comment by larsbrinkhoff** [comment]
Thanks, and good luck!

**Comment by drom** [comment]
I have submitted here: https://github.com/sindresorhus/awesome/pull/807

**Comment by larsbrinkhoff** [comment]
Great!  I think we can consider this closed.  Feel free to create new issues if there are any problems.
