### ISSUE TITLE
Group CPUs

### ISSUE THREAD

**Issue by drom** [larsbrinkhoff/awesome-cpus#19]
Does it make sense to group CPUs by the original vendor?
At least the main ones: DEC, Motorola, Intel, IBM, TI

**Comment by larsbrinkhoff** [comment]
Maybe!  I'm not sure.  There are many one-off architectures.  And vendors buy each other, and change names, etc.  AVR used to be Atmel, now it's Microchip.  Motorola became Freescale and is now NXP.  DEC is no more.

Sure "original vendor" would mean something.  But is this repository for documenting hisstorical facts, or providing contemporary information?

**Comment by larsbrinkhoff** [comment]
I think an alphabetical list is simple to maintain - no maintenance at all if it's just the directory listing.

**Comment by larsbrinkhoff** [comment]
Closing for now.  Feel free to reopen if you have any more ideas about this.e
