### ISSUE TITLE
Add Schematic/Circuit For Each CPUs As Logic Gate

### ISSUE THREAD

**Issue by cheznewa** [larsbrinkhoff/awesome-cpus#33]
Hello, Is Possible To Add Schematic (Or Circuit) As Logic Gate?
Made With Software Like [SmartSim](https://github.com/ashleynewson/SmartSim) Or [LogicEmu](https://github.com/lvandeve/logicemu) (My Favorite) According To Their Datasheet.

Thanks!

Newa Our Master.

**Comment by larsbrinkhoff** [comment]
I don't think it would be appropriate to add schematics.
