### ISSUE TITLE
MCS-96 809X-90, 809X-90 families

### ISSUE THREAD

**Issue by TG9541** [larsbrinkhoff/awesome-cpus#36]
The, once prolific, MCS-96 family has dropped out of sight. If you're interested I have some docs about the "old" MCS-96 families here (including instruction set), and an "Introduction to the 8XC196KC/KD (maybe more if I spend some more time searching).

![image](https://user-images.githubusercontent.com/5466977/121805794-fa120d80-cc4c-11eb-8fbd-1a2c30c18b0f.png)

**Comment by larsbrinkhoff** [comment]
Yes, all families are welcome here!
