### ISSUE TITLE
WDC 65C02 pin 1 is VPB instead of VSS

### ISSUE THREAD

**Issue by wyatt-wong** [larsbrinkhoff/awesome-cpus#38]
I noticed the pin 1 of 65C02.txt file is marked as VSS but according to the WDC datasheeet of 65C02, pin 1 should be VPB (Vector Pull) instead

https://github.com/larsbrinkhoff/awesome-cpus/blob/master/MCS6500/65c02.txt

**Comment by larsbrinkhoff** [comment]
Can you please submit a pull request?

**Comment by wyatt-wong** [comment]
Sorry I am not familiar in using pull request. I have just submitted one pull request but I found that I cannot submit another pull request in the mean time.

**Comment by larsbrinkhoff** [comment]
No problem, we can do one at a time.

**Comment by wyatt-wong** [comment]
According to the pages 12-13 of the WDC W65C02S datasheet of Feb 25 2020, the WDC W65C02S pin 1 is VPB (Vector Pull) while the pin 1 of the 65C02 manufactured by other vendors are VSS, I would suggest to duplicate the https://github.com/larsbrinkhoff/awesome-cpus/blob/master/MCS6500/65c02.txt file and create another text file specific for WDC 65C02

![image](https://user-images.githubusercontent.com/10095648/140876901-162a83b3-03c4-4d5b-8d1f-0703f3084856.png)
![image](https://user-images.githubusercontent.com/10095648/140876974-1805bd8e-49a2-4081-9c9d-1114883a5e0e.png)

**Comment by wyatt-wong** [comment]
Propose to rename 65c02.txt to rockwell 65c02.txt
