### ISSUE TITLE
Can we add Intel 8086?

### ISSUE THREAD

**Issue by feldrim** [larsbrinkhoff/awesome-cpus#5]
I know it's almost the same as 8085, which already exists on the repo but it'd be nice to have it there. I've found [this one ](http://www.ece.cmu.edu/~ece740/f11/lib/exe/fetch.php?media=wiki:8086-datasheet.pdf)about 8086, 8086-1, 8086-2.

**Comment by The-Blue-Wizard** [comment]
feldrim, 8086 is **most definitely not** "almost the same" as 8085! Not by a mile!!! But I do notice that while there's x86-64, but there is no manuals for 16 and 32 bit versions. I have old text docs for 80386...should I upload them? If so, what is the best way to do it?

**Comment by larsbrinkhoff** [comment]
We can certainly add 8086 and its decendants.  Maybe there should be a single `x86` directory with all variants?

**Comment by larsbrinkhoff** [comment]
So, the answer is YES WE CAN.
