### ISSUE TITLE
Suggest that README.md files be added...

### ISSUE THREAD

**Issue by The-Blue-Wizard** [larsbrinkhoff/awesome-cpus#6]
I would suggest that a README.md be added to the main level, and every subfolder have its own README.md as well. Each README.md should contain a brief description of the CPU, plus a link to Wikipedia article and a source from where the documents are taken from, if possible. Comments/thoughts?

**Comment by larsbrinkhoff** [comment]
There should absolutely be a top-level README, and other supporting documents.

As for subdirectory READMEs, that's a great idea, but a lot of work.  Pull requests accepted!

**Comment by larsbrinkhoff** [comment]
This is in progress.  Thanks @The-Blue-Wizard!
