### ISSUE TITLE
Policies for adding documents?

### ISSUE THREAD

**Issue by The-Blue-Wizard** [larsbrinkhoff/awesome-cpus#7]
I have a bunch of various CPU documents, etc., and while I would be happy to upload them, but I am not sure what I can do. For example, I have a Z80 PDF manual, and I checked it against yours, and I found mine to be a bit newer, with a few revisions mentioned in that document. Would that be acceptable? I also have a few ASCII "cards", especially for 6502 and one or two other 8-bit CPUs. Would they be acceptable as well? I also have a few files of my own making that might be useful as well...are they OK to be uploaded too? Thanks for the clarifications!

**Comment by larsbrinkhoff** [comment]
My only concern is the 1G limit on the size of the repository that GitHub imposes.  Other than that, I'm happy to include all kinds of documents.  The ones you mention sound fine.

**Comment by slorquet** [comment]
So why not drop github and go elsewhere? like, just... storage instead of git?

I know plenty of doc: MCS51, MCS151, MCS251, etc

Do you want docs for system on chip, or just architecture docs?

**Comment by larsbrinkhoff** [comment]
I kinda like GitHub, because it's a go-to place for many developers.  Sure, I could host the documents anywhere, but then it'd just be another website which no one cares about.

I prefer architecture docs.  I do have many implementation-specific docs too, but I don't see the point in trying to collect info on every single chip ever made.  However, there's no specific rule at this point.

**Comment by slorquet** [comment]
okay, makes sense.

here are some goodies
http://www.keil.com/dd/docs/datashts/intel/8xc251sx_um.pdf
http://www.sharpmz.org/download/8048.pdf

You also need 6502 stuff!

**Comment by larsbrinkhoff** [comment]
@slorquet Those look good!  Can you make a pull request?

**Comment by f4grx** [comment]
Are you seriously asking me to download the full repo (sth I did not intend to do) instead of using your currently opened browser to download 2 files to your current setup?

I dont care AT ALL about having my name in the history.

**Comment by larsbrinkhoff** [comment]
I added [Contribution Guidelines](contributing.md).
